Sarif genesis
projectdiscovery/sarif pull request #1
Opened 2022-11-25 20:09 UTC by tarunKoyalwar

# Description

- Simple and Standard Implementation of SARIF for nuclei 
- Supports both Import & Export

- Create an example report by running

```sh
  go run example/main.go
```

It can be viewed using VSCode Sarif Extension or at [sarif-webcomponent](https://microsoft.github.io/sarif-web-component/)

<img width="570" alt="Screenshot 2022-11-26 at 1 30 46 AM" src="https://user-images.githubusercontent.com/45962551/204051034-e4095ba0-283c-4ebb-b8e7-a76558f45ef1.png">

2022-11-25 20:10 UTC, tarunKoyalwar commented
Implemented for https://github.com/projectdiscovery/nuclei/issues/2608

2022-11-25 20:14 UTC, tarunKoyalwar commented
With Implementation of Sarif output of [nuclei-gh-action] can be viewed in Security/Code-Scanning-Results of a repository.

as requested at https://github.com/projectdiscovery/nuclei-action/issues/43

something similar to https://www.youtube.com/watch?v=4MduRFoKpGY

2022-11-29 09:28 UTC, Mzack9999 requested changes
lgtm - minor changes requested

2022-11-29 09:28 UTC, Mzack9999 commented on example/main.go
> +
extra line

2022-11-29 09:28 UTC, Mzack9999 commented on go.mod
> +go 1.19
we still target go 1.18

2022-11-29 09:39 UTC, Mzack9999 approved these changes

2022-11-29 09:41 UTC, merged